FROM node:20-alpine AS build

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY index.html vite.config.mjs ./
COPY vite.node.d.ts ./
COPY tsconfig.json tsconfig.app.json tsconfig.node.json ./
COPY src src
COPY shared shared

RUN corepack enable
RUN pnpm install --no-frozen-lockfile
RUN pnpm build:web

FROM nginx:1.27-alpine AS runtime

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
